steps:  
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['build', '-t', 'us-central1-docker.pkg.dev/de-ci-445005/docker-ci-demo-repo/my-app:${SHORT_SHA}', '.' ] 
    logsBucket: 'gs://de-ci-demo-storage'

  - name: 'gcr.io/cloud-builders/docker'  
    args: ['push', 'us-central1-docker.pkg.dev/de-ci-445005/docker-ci-demo-repo/my-app:${SHORT_SHA}']  

images:   
  - us-central1-docker.pkg.dev/de-ci-445005/docker-ci-demo-repo/my-app:${SHORT_SHA} 

